### ISSUE TITLE
Type Error

### ISSUE THREAD

**Issue by dev-2null** [3v4Si0N/HTTP-revshell#1]
Hi, I got following error for HTTP connection:
```
Exception happened during processing of request from ('[IP]', 47964)
Traceback (most recent call last):
  File "/usr/lib/python3.5/socketserver.py", line 313, in _handle_request_noblock
    self.process_request(request, client_address)
  File "/usr/lib/python3.5/socketserver.py", line 341, in process_request
    self.finish_request(request, client_address)
  File "/usr/lib/python3.5/socketserver.py", line 354, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/lib/python3.5/socketserver.py", line 681, in __init__
    self.handle()
  File "/usr/lib/python3.5/http/server.py", line 422, in handle
    self.handle_one_request()
  File "/usr/lib/python3.5/http/server.py", line 410, in handle_one_request
    method()
  File "./server.py", line 30, in do_POST
    result, parser_type, json_response, color = self.parseResult()
  File "./server.py", line 50, in parseResult
    data = json.loads(test_data)
  File "/usr/lib/python3.5/json/__init__.py", line 312, in loads
    s.__class__.__name__))
TypeError: the JSON object must be str, not 'bytes'
```
Any idea?

**Comment by dev-2null** [comment]
https://github.com/3v4Si0N/HTTP-revshell/blob/master/server.py#L50
Change `data = json.loads(test_data)` to `data = json.loads(test_data.decode('utf-8'))`
This will work

**Comment by 3v4Si0N** [comment]
Thanks dev-2null for your issue and solution. I'll change It ;)
